spring.application.name=spotifou
spring.datasource.url=jdbc:postgresql://localhost:5432/spotifou
spring.datasource.username=spotifou
spring.datasource.password=change_me
spring.jpa.hibernate.ddl-auto=update