spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spotifou
    username: spotifou
    password: change_me
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
